[package]
name = "bevy_sandbox"
version = "0.1.0"
authors = ["Sean Kaufman <sean.kaufman92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.2"
paste = "1.0"